# Generated by Django 6.0.5 on 2026-05-28 18:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('document_type', models.CharField(choices=[('loan_application', 'Loan Application'), ('kyc', 'KYC Document'), ('compliance', 'Compliance Report'), ('account_statement', 'Account Statement'), ('risk_assessment', 'Risk Assessment')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=100)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('document_review', 'Document Review'), ('compliance_check', 'Compliance Check'), ('approval_request', 'Approval Request'), ('risk_assessment', 'Risk Assessment')], max_length=50)),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='banking.bankingdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
